all : Connection.class CommandType.class FClient.class FClientCommandLine.class FileIO.class GenerateTest.class MainFS.class Proxy1.class Proxy2.class Proxy.class ProxyFile.class Server.class

clean :
	rm -f *.class
doc :
	javadoc -d doc *.java

Connection.class : Connection.java
	javac Connection.java
CommandType.class : CommandType.java
	javac CommandType.java
FClient.class : FClient.java
	javac FClient.java
FClientCommandLine.class : FClientCommandLine.java
	javac FClientCommandLine.java
FileIO.class : FileIO.java
	javac FileIO.java
GenerateTest.class : GenerateTest.java
	javac GenerateTest.java
MainFS.class : MainFS.java
	javac MainFS.java
Proxy1.class : Proxy1.java
	javac Proxy1.java
Proxy2.class : Proxy2.java
	javac Proxy2.java
Proxy.class : Proxy.java
	javac Proxy.java
ProxyFile.class : ProxyFile.java
	javac ProxyFile.java
Server.class : Server.java
	javac Server.java

